# Generated by Django 2.0 on 2021-02-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='type',
            field=models.TextField(),
        ),
    ]
